// flow-typed signature: 38484269004023561cd35571a21d47c0
// flow-typed version: <<STUB>>/gatsby-remark-autolink-headers_v1.4.13/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-autolink-headers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-autolink-headers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-remark-autolink-headers/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-remark-autolink-headers/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-remark-autolink-headers/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-remark-autolink-headers/gatsby-browser'>;
}
declare module 'gatsby-remark-autolink-headers/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-remark-autolink-headers/gatsby-ssr'>;
}
declare module 'gatsby-remark-autolink-headers/index' {
  declare module.exports: $Exports<'gatsby-remark-autolink-headers'>;
}
declare module 'gatsby-remark-autolink-headers/index.js' {
  declare module.exports: $Exports<'gatsby-remark-autolink-headers'>;
}
