// flow-typed signature: 77c56c0e67dc8f65659ead2e0124b445
// flow-typed version: <<STUB>>/gatsby-remark-external-links_v0.0.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-external-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-external-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-external-links/index' {
  declare module.exports: $Exports<'gatsby-remark-external-links'>;
}
declare module 'gatsby-remark-external-links/index.js' {
  declare module.exports: $Exports<'gatsby-remark-external-links'>;
}
