// flow-typed signature: 580d8a21d81f9fab7b7fa8bc5c20cd07
// flow-typed version: <<STUB>>/gatsby-image_v1.0.34/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-image/fragments' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-image/fragments.js' {
  declare module.exports: $Exports<'gatsby-image/fragments'>;
}
declare module 'gatsby-image/index' {
  declare module.exports: $Exports<'gatsby-image'>;
}
declare module 'gatsby-image/index.js' {
  declare module.exports: $Exports<'gatsby-image'>;
}
