// flow-typed signature: 4fb9b7f60100bb0037ac7d11f9bad45a
// flow-typed version: <<STUB>>/gatsby-plugin-typography_v1.7.11/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-typography' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-typography/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typography/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typography/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-typography/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-typography/gatsby-browser'>;
}
declare module 'gatsby-plugin-typography/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-typography/gatsby-node'>;
}
declare module 'gatsby-plugin-typography/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-typography/gatsby-ssr'>;
}
declare module 'gatsby-plugin-typography/index' {
  declare module.exports: $Exports<'gatsby-plugin-typography'>;
}
declare module 'gatsby-plugin-typography/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-typography'>;
}
