// flow-typed signature: ad0c3cc916acda6bfead263f732f5630
// flow-typed version: <<STUB>>/gatsby-remark-emoji_v0.0.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-emoji/index' {
  declare module.exports: $Exports<'gatsby-remark-emoji'>;
}
declare module 'gatsby-remark-emoji/index.js' {
  declare module.exports: $Exports<'gatsby-remark-emoji'>;
}
