// flow-typed signature: fea12cd3206b806e6a464b4f3cc2ddcf
// flow-typed version: <<STUB>>/param-case_v2.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'param-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'param-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'param-case/param-case' {
  declare module.exports: any;
}

// Filename aliases
declare module 'param-case/param-case.js' {
  declare module.exports: $Exports<'param-case/param-case'>;
}
