// flow-typed signature: 7baeb38d9ae2d4c8591c94200538b1d6
// flow-typed version: <<STUB>>/react-aux_v1.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-aux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-aux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-aux/src/Aux' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-aux/src/Aux.js' {
  declare module.exports: $Exports<'react-aux/src/Aux'>;
}
