// flow-typed signature: 12abdc74ee3606bab627f76bd33975a6
// flow-typed version: <<STUB>>/stylelint-config-styled-components_v0.1.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-styled-components/index' {
  declare module.exports: $Exports<'stylelint-config-styled-components'>;
}
declare module 'stylelint-config-styled-components/index.js' {
  declare module.exports: $Exports<'stylelint-config-styled-components'>;
}
